name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          npm install
      - name: lint
        run: |
          npm lint
      - name: test
        run: |
          npm test
      - name: build
        run: |
          npm rakenna
      - uses: akhileshns/heroku-deploy@v3.2.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "coolest-of-tests"
          heroku_email: "riku.laukkanen@smartly.io"